[package]
name = "adam_regex"
version = "0.1.0"
edition = "2021"

[lib]
name = "adam_regex"
path = "src/lib.rs"

[dev-dependencies]
criterion = "0.7.0"
regex = "1"

[[bench]]
name = "regex_bench"
harness = false

[dependencies]
bit-set = "0.8.0"
